namespace Home.Core.Models
{
    public enum EModule
    {
        IrRemoteControl,
        IrOptocoupler,
        ColorSensor,
        DistanceSensor,
        LightSensor,
        Button,
        TemperatureSensor,
        MicrophoneAnalog,
        ThresholdMicrophone,
        PositionSensor,
        ShaftAngleSensor,
        TiltSensor,
        ShockSensor,
        FireSensor,
        MagneticFieldSensor,
        BendingSensor,
        Neurohoop,
        HdCamera,
        DcMotor,
        ServoMotor,
        Display,
        Led,
        Speaker,
        Buzzer,
        AudioTrack
    }
}
