name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build_api:

    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v2
#     - name: Stopping working Instance
#       run: docker stop myapp
#     - name: Remove Instance
#       run: docker rm myapp
#     - name: Remove Image
#       run: docker rmi webapi -f
    - name: Build the Docker image
      run: docker build -f DockerfileApi . -t webapi
    - name: Run Docker image
      run: docker run -d -p 8080:80 --name myapp webapi
      
      
  build_front:

    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker-compose -f docker-compose.yaml build
    - name: Run Docker image
      run: docker-compose -f docker-compose.yaml up -d

